# Generated by Django 4.1.3 on 2025-01-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='learned_users',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='image_url',
            field=models.CharField(default='http://example.com/default_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='learned_words',
            field=models.ManyToManyField(related_name='learned_by', to='group8.word'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
