# Generated by Django 4.1.3 on 2025-01-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group8', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image_url',
        ),
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default='word_images/default_image.jpg', upload_to='word_images/'),
        ),
    ]
