# Generated by Django 4.1.3 on 2025-01-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group8', '0004_alter_word_image_url_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
