# Generated by Django 4.1.3 on 2025-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group8', '0004_alter_word_image_url_request'),
        ('group8', '0005_request'),
    ]

    operations = [
    ]
