# Generated by Django 4.1.3 on 2025-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group8', '0006_merge_0004_alter_word_image_url_request_0005_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
    ]
